# Generated by Django 2.0 on 2017-12-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('feedback', models.BooleanField()),
                ('all_buttons', models.BooleanField()),
                ('lighting_time', models.IntegerField()),
                ('interval_time', models.IntegerField()),
                ('session_time', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='experiment',
            field=models.ForeignKey(on_delete=True, to='core.Experiment'),
        ),
    ]
