# Generated by Django 2.0 on 2018-01-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_event', models.CharField(max_length=256)),
                ('time', models.IntegerField()),
                ('trial', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('is_male', models.BooleanField()),
                ('age', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('time_to_red', models.IntegerField()),
                ('time_train_gil', models.IntegerField()),
                ('time_test_gil', models.IntegerField()),
                ('time_train_cards', models.IntegerField()),
                ('welcome', models.TextField()),
                ('instr_gil', models.TextField()),
                ('instr_cards', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('Q', models.TextField()),
                ('nQ', models.TextField()),
                ('P', models.TextField()),
                ('nP', models.TextField()),
                ('rule', models.TextField()),
                ('instruction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskRandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=0)),
                ('trial', models.BooleanField()),
                ('content', models.TextField()),
                ('Q', models.TextField()),
                ('nQ', models.TextField()),
                ('P', models.TextField()),
                ('nP', models.TextField()),
                ('rule', models.TextField()),
                ('instruction', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=True, to='core.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),
        migrations.AddField(
            model_name='event',
            name='experiment',
            field=models.ForeignKey(on_delete=True, to='core.Experiment'),
        ),
        migrations.AddField(
            model_name='event',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='core.TaskRandom'),
        ),
    ]
