# Generated by Django 2.0.1 on 2018-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='my_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
