# Generated by Django 2.0 on 2017-12-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='interval_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='lighting_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='session_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
