# Generated by Django 2.0 on 2017-12-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171216_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
