# Generated by Django 2.0.1 on 2018-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180122_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='is_male',
            field=models.NullBooleanField(),
        ),
    ]
