# Generated by Django 2.0 on 2017-12-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171216_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='trial',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
