# Generated by Django 2.0.1 on 2018-02-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_experiment_instr_test_gil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.FloatField(),
        ),
    ]
