# Generated by Django 2.0 on 2017-12-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sequence_trial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='done',
            new_name='is_done',
        ),
    ]
